services:
  butterfly:
    image: clovetwilight3/butterfly-network
    ports:
      - "8004:8004"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
  
#  clovetwilight3.co.uk:
#    build:
#      context: ./clovetwilight3.co.uk
#      dockerfile: Dockerfile
#    ports:
#      - "8005:8005"
#    environment:
#      - NODE_ENV=production
#    restart: unless-stopped

  lgbt:
    image: clovetwilight3/lgb-with-t
    ports:
      - "8008:8008"
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  mazeymoos:
    image: clovetwilight3/estrogen-moos:latest
    ports:
      - "8006:8006"
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  midnight:
    image: clovetwilight3/themidnightcyan:latest
    ports:
      - "8007:8007"
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  dough-back:
    image: clovetwilight3/doughmination-backend:latest
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - backend_data:/app/data
      - backend_avatars:/app/avatars
    restart: unless-stopped

  dough-front:
    image: clovetwilight3/doughmination-frontend:latest
    ports:
      - "8001:8001"
    depends_on:
      - dough-back
    restart: unless-stopped

  t4t:
    build:
      context: ./trans4trans.win/backend
      dockerfile: Dockerfile
    ports:
      - "8003:8003"
    restart: unless-stopped
    env_file:
      - .env

  yuri:
    build:
      context: ./yuri-lover.win
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: unless-stopped

  discord:
    image: ghcr.io/the-snesler/discord-github-preview:latest
    ports:
      - "8002:3000"
    env_file: .env
    restart: unless-stopped

volumes:
  backend_data:
  backend_avatars: