name: Approve and Merge Dependabot Updates

on:
  workflow_dispatch:

permissions:
  pull-requests: write
  contents: read

jobs:
  approve-and-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install @octokit/rest
        run: npm install @octokit/rest

      - name: Approve and merge Dependabot PRs
        run: |
          node - <<'EOF'
          const { Octokit } = require("@octokit/rest");

          const octokit = new Octokit({
            auth: process.env.BOT_PAT
          });

          async function run() {
            const [owner, repo] = process.env.GITHUB_REPOSITORY.split("/");

            // Fetch open Dependabot PRs
            const { data: pulls } = await octokit.pulls.list({
              owner,
              repo,
              state: "open",
            });

            for (const pr of pulls) {
              if (pr.user.login === "dependabot[bot]") {
                console.log(`Approving PR #${pr.number}: ${pr.title}`);
                await octokit.pulls.createReview({
                  owner,
                  repo,
                  pull_number: pr.number,
                  event: "APPROVE",
                });

                console.log(`Merging PR #${pr.number}`);
                try {
                  await octokit.pulls.merge({
                    owner,
                    repo,
                    pull_number: pr.number,
                    merge_method: "squash" // or "merge" or "rebase"
                  });
                  console.log(`PR #${pr.number} merged successfully`);
                } catch (err) {
                  console.error(`Failed to merge PR #${pr.number}:`, err.message);
                }
              }
            }
          }

          run().catch(err => {
            console.error(err);
            process.exit(1);
          });
          EOF
        env:
          BOT_PAT: ${{ secrets.BOT_PAT }}